name: Dev build and publish Java distributions to sonatype snapshot repository and ghcr

on:
  push:
    branches-ignore:
      - master
      - version-*

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java-dev.yml@main
    with:
      build-target: 'Sonatype,Docker'
      runsOn: ubuntu-latest
      docker-username: ${{ github.actor }}
      javaVersion: '17'
    secrets:
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
      docker-password: ${{ secrets.GITHUB_TOKEN }}
