name: Build and publish Docker distributions to Github Container Registry ghcr.io

on:
  push:
    branches:
      - master
    paths:
      - gradle.properties

jobs:
  build:
    uses: th2-net/.github/.github/workflows/compound-java.yml@main
    with:
      build-target: 'Sonatype,Docker'
      runsOn: ubuntu-latest
      docker-username: ${{ github.actor }}
      javaVersion: '11'
    secrets:
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
      docker-password: ${{ secrets.GITHUB_TOKEN }}
