name: Build and publish Docker distributions to Github Container Registry ghcr.io

on:
  push:
    branches:
      - java-11
    paths:
      - gradle.properties

jobs:
  build:
    uses: th2-net/.github/.github/workflows/compound-java.yml@main
    with:
#     java 11 version is used only as maven dependency
      build-target: 'Sonatype'
      runsOn: ubuntu-latest
    secrets:
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}